"""Multi-scenario strategy contracts, routing, and Advice construction."""

from .advice import (
    Advice,
    AdviceStatus,
    build_advice,
    mark_stale,
)
from .adaptive_equity import (
    AdaptiveEquityPolicy,
    AdaptiveEquityReport,
    EquityComputationStatus,
    calculate_adaptive_equity,
)
from .asset_provider import (
    JsonStrategyAssetProvider,
    STRATEGY_ASSET_SCHEMA_VERSION,
    provider_capability_digest,
)
from .contracts import (
    ActionAmountSemantics,
    ContextQuality,
    DecisionContext,
    DecisionSeat,
    EffectiveStack,
    GameConfig,
    GameType,
    InputProvenance,
    InputSource,
    LegalAction,
    PotState,
    QualityStatus,
    RangeDistribution,
)
from .context_factory import (
    ContextQualityPolicy,
    RequestContextFactory,
    aggregate_context_quality,
)
from .confidence import ConfidenceAggregate, aggregate_confidence
from .blueprint_provider import (
    BlueprintLoaderLike,
    HuPreflopBlueprintProvider,
    PROVIDER_ID as HU_BLUEPRINT_PROVIDER_ID,
    action_history_token,
    hand_class,
)
from .equity_cache import (
    EquityCache,
    EquityCacheEntry,
    EquityCacheLookup,
    EquityCacheQuery,
    EquityCacheState,
    EquityMethod,
)
from .evidence import (
    EvidenceAudit,
    EvidenceAuditPolicy,
    EvidenceReference,
    EvidenceStage,
    audit_evidence_chain,
)
from .explanation import AdviceExplanation, explain_advice
from .exploit_fusion import (
    ExploitAdjustment,
    ExploitAdjustmentPolicy,
    ExploitAdjustmentStatus,
    adjust_for_opponent,
)
from .fusion import DecisionFusion, FusionOutcome, OpponentAdjustmentInput
from .heuristic_provider import (
    ASSET_NAME as PREFLOPR_ASSET_NAME,
    PROVIDER_ID as PREFLOPR_PROVIDER_ID,
    PreflopRfiHeuristicProvider,
)
from .gtopen_provider import (
    ADAPTER_VERSION as GTOPEN_ADAPTER_VERSION,
    PROVIDER_ID as GTOPEN_PROVIDER_ID,
    GTOpenConfig,
    GTOpenError,
    GTOpenPreflopProvider,
    GTOpenTransport,
    UrlLibGTOpenTransport,
    gtopen_hand_class_index,
)
from .ev import (
    ActionEvEstimate,
    EvGapResult,
    EvStatus,
    calculate_aggressive_ev,
    calculate_call_ev,
    calculate_ev_gap,
)
from .provider import (
    ActionOption,
    FakeProvider,
    LookupState,
    MatchDimension,
    MatchKind,
    ProviderCapability,
    ProviderResult,
    StrategyCandidate,
    StrategyProvider,
)
from .multiway_equity import (
    MonteCarloMultiwayResult,
    MultiwayEquityResult,
    PotEquity,
    exact_multiway_pot_share,
    monte_carlo_multiway_pot_share,
    monte_carlo_multiway_ranges,
)
from .metrics import (
    MetricStatus,
    NormalizedActionSize,
    PairwiseSpr,
    PotOddsMetric,
    calculate_pairwise_spr,
    calculate_pot_odds,
    normalize_action_size,
)
from .local_resolver import (
    LocalResolverConfig,
    LocalResolverProvider,
    RESOLVER_PROTOCOL_VERSION,
)
from .input_provenance import (
    ProvenanceCandidate,
    ProvenanceCollection,
    SuppliedInput,
    candidate_from_observation,
    canonical_value_digest,
    collect_input_provenance,
)
from .orchestration import (
    RefinementState,
    SlowHandle,
    SlowRefinement,
    SlowResolver,
    StrategyCycle,
    StrategyOrchestrator,
    ThreadedSlowResolver,
)
from .range_tracker import (
    JointRangeAssignment,
    RangeUpdate,
    bayesian_action_update,
    enumerate_joint_assignments,
    filter_blocked_combos,
    parse_concrete_combo,
    shrink_action_likelihoods,
)
from .range_prior import (
    PreflopRfiRangePrior,
    RangePriorQuery,
    RangePriorResult,
    RangePriorState,
    expand_hand_class,
)
from .router import (
    FastSourceLayer,
    RouteResult,
    StrategyRouteProvider,
    StrategyRouter,
    TieredStrategyRouter,
)
from .serialization import (
    STRATEGY_SCHEMA_VERSION,
    strategy_deserialize,
    strategy_serialize,
)
from .safety import GateResult, GateStatus, validate_gate_set
from .state import (
    PotCalculation,
    build_decision_context,
    calculate_legal_actions,
    calculate_side_pots,
)
from .strategy_cache import (
    CachingStrategyProvider,
    StrategyCache,
    StrategyCacheEntry,
    StrategyCacheLookup,
    StrategyCacheQuery,
    StrategyCacheState,
    StrategyCacheProvider,
    StrategyTemplate,
    canonical_context_digest,
)
from .training import (
    ActualActionRecord,
    HandDebrief,
    HandReview,
    build_hand_debrief,
    build_hand_review,
)

__all__ = [
    "Advice",
    "AdviceExplanation",
    "AdviceStatus",
    "ActualActionRecord",
    "AdaptiveEquityPolicy",
    "AdaptiveEquityReport",
    "ActionAmountSemantics",
    "ActionOption",
    "ActionEvEstimate",
    "BlueprintLoaderLike",
    "CachingStrategyProvider",
    "ContextQuality",
    "ContextQualityPolicy",
    "ConfidenceAggregate",
    "DecisionContext",
    "DecisionFusion",
    "DecisionSeat",
    "EffectiveStack",
    "EquityCache",
    "EquityCacheEntry",
    "EquityCacheLookup",
    "EquityCacheQuery",
    "EquityCacheState",
    "EquityComputationStatus",
    "EquityMethod",
    "EvidenceAudit",
    "EvidenceAuditPolicy",
    "EvidenceReference",
    "EvidenceStage",
    "EvGapResult",
    "EvStatus",
    "ExploitAdjustment",
    "ExploitAdjustmentPolicy",
    "ExploitAdjustmentStatus",
    "FakeProvider",
    "FastSourceLayer",
    "FusionOutcome",
    "GameConfig",
    "GameType",
    "GateResult",
    "GateStatus",
    "GTOPEN_ADAPTER_VERSION",
    "GTOPEN_PROVIDER_ID",
    "GTOpenConfig",
    "GTOpenError",
    "GTOpenPreflopProvider",
    "GTOpenTransport",
    "HU_BLUEPRINT_PROVIDER_ID",
    "HandDebrief",
    "HandReview",
    "HuPreflopBlueprintProvider",
    "InputProvenance",
    "InputSource",
    "JointRangeAssignment",
    "JsonStrategyAssetProvider",
    "LegalAction",
    "LookupState",
    "LocalResolverConfig",
    "LocalResolverProvider",
    "MatchKind",
    "MatchDimension",
    "MetricStatus",
    "MonteCarloMultiwayResult",
    "MultiwayEquityResult",
    "NormalizedActionSize",
    "OpponentAdjustmentInput",
    "PotState",
    "PotCalculation",
    "PotEquity",
    "PotOddsMetric",
    "ProvenanceCandidate",
    "ProvenanceCollection",
    "PreflopRfiRangePrior",
    "PREFLOPR_ASSET_NAME",
    "PREFLOPR_PROVIDER_ID",
    "PreflopRfiHeuristicProvider",
    "ProviderCapability",
    "ProviderResult",
    "PairwiseSpr",
    "QualityStatus",
    "RangeDistribution",
    "RangePriorQuery",
    "RangePriorResult",
    "RangePriorState",
    "RangeUpdate",
    "RESOLVER_PROTOCOL_VERSION",
    "RequestContextFactory",
    "RefinementState",
    "RouteResult",
    "SlowHandle",
    "SlowRefinement",
    "SlowResolver",
    "StrategyCandidate",
    "StrategyCache",
    "StrategyCacheEntry",
    "StrategyCacheLookup",
    "StrategyCacheQuery",
    "StrategyCacheState",
    "StrategyCacheProvider",
    "StrategyCycle",
    "StrategyOrchestrator",
    "StrategyProvider",
    "StrategyRouteProvider",
    "StrategyRouter",
    "StrategyTemplate",
    "SuppliedInput",
    "ThreadedSlowResolver",
    "TieredStrategyRouter",
    "UrlLibGTOpenTransport",
    "STRATEGY_SCHEMA_VERSION",
    "STRATEGY_ASSET_SCHEMA_VERSION",
    "build_advice",
    "candidate_from_observation",
    "canonical_value_digest",
    "collect_input_provenance",
    "action_history_token",
    "aggregate_context_quality",
    "aggregate_confidence",
    "adjust_for_opponent",
    "audit_evidence_chain",
    "bayesian_action_update",
    "build_decision_context",
    "build_hand_debrief",
    "build_hand_review",
    "calculate_legal_actions",
    "calculate_adaptive_equity",
    "calculate_aggressive_ev",
    "calculate_call_ev",
    "calculate_ev_gap",
    "calculate_pairwise_spr",
    "calculate_pot_odds",
    "calculate_side_pots",
    "canonical_context_digest",
    "enumerate_joint_assignments",
    "expand_hand_class",
    "exact_multiway_pot_share",
    "explain_advice",
    "filter_blocked_combos",
    "gtopen_hand_class_index",
    "hand_class",
    "mark_stale",
    "monte_carlo_multiway_pot_share",
    "monte_carlo_multiway_ranges",
    "normalize_action_size",
    "parse_concrete_combo",
    "provider_capability_digest",
    "shrink_action_likelihoods",
    "strategy_deserialize",
    "strategy_serialize",
    "validate_gate_set",
]
